name: Deploy to Render with GitHub Deployment and Polling

on:
  push:
    branches:
      - main  # Altere se usar outro branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub Deployment
        id: create_deployment
        uses: peter-evans/create-or-update-deployment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: production
          ref: ${{ github.sha }}
          transient_environment: false
          auto_merge: false

      - name: Trigger Render Deploy
        id: trigger_render
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://api.render.com/deploy/srv-d1iunmh5pdvs73choma0
          method: POST
          headers: |
            Authorization: Bearer ${{ secrets.RENDER_API_KEY }}
            Content-Type: application/json

      - name: Extract deploy ID from Render response
        id: extract_deploy_id
        run: |
          echo '${{ steps.trigger_render.outputs.response-body }}' > response.json
          DEPLOY_ID=$(jq -r '.id' response.json)
          echo "deploy_id=$DEPLOY_ID" >> $GITHUB_OUTPUT

      - name: Poll Render deploy status
        id: poll_status
        run: |
          DEPLOY_ID=${{ steps.extract_deploy_id.outputs.deploy_id }}
          echo "Polling deploy status for ID: $DEPLOY_ID"

          for i in {1..15}; do
            RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
              https://api.render.com/deploy/${DEPLOY_ID})

            STATE=$(echo "$RESPONSE" | jq -r '.state')
            echo "Attempt $i: state = $STATE"

            if [[ "$STATE" == "READY" ]]; then
              echo "Deploy succeeded"
              echo "deploy_status=success" >> $GITHUB_OUTPUT
              exit 0
            elif [[ "$STATE" == "ERROR" ]]; then
              echo "Deploy failed"
              echo "deploy_status=failure" >> $GITHUB_OUTPUT
              exit 1
            fi

            echo "Deploy in progress... waiting 15 seconds"
            sleep 15
          done

          echo "Timeout waiting deploy finish"
          echo "deploy_status=failure" >> $GITHUB_OUTPUT
          exit 1

      - name: Update GitHub Deployment status
        run: |
          DEPLOYMENT_ID=${{ steps.create_deployment.outputs.deployment_id }}
          STATUS=${{ steps.poll_status.outputs.deploy_status }}

          if [[ "$STATUS" == "success" ]]; then
            STATE="success"
          else
            STATE="failure"
          fi

          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/deployments/$DEPLOYMENT_ID/statuses \
            -d "{\"state\":\"$STATE\"}"
